#!/usr/bin/env bash
# Shows 1-20 with superstitious messages on 4, 9, 17
i=1

while [ $i -le 20 ]; do

	echo $i

	case $i in 

		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;

	esac

	((i++))

done
