#!/usr/bin/env bash
# Process and PID file

file="/var/run/myscript.pid"
touch file
trap 'echo "I hate the kill command" rm "$file" exit 1' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$file" exit 1' SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
