#!/usr/bin/env bash
# stop me if you can


pkill -15 -f "7-highlander"
~                                                                                  
~                                                                                  
~                                                                                  
~                                                                                  
~                                                                                  
~
